// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixRoundPlayer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixRoundPlayer));
        
        string IMigrationMetadata.Id
        {
            get { return "201806061159567_fixRoundPlayer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
